name: deel_globepay

version: '1.0.0'

config-version: 2

profile: snowflake

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
 - "target"
 - "dbt_packages"

models:
  deel_globepay:
    src:
      +materialized: view         # Source models
    staging:
      +materialized: view         # Cleaned/parsed
    intermediate:
      +materialized: ephemeral   
    analytics:
      +materialized: table        # BI-ready facts & dimensions